language: node_js
node_js:
- '6'
script:
- npm run lint
- npm test
- npm run build
deploy:
  provider: npm
  email: opensource@yousee.dk
  skip_cleanup: true
  api_key: 
    secure: ZpFF/xbGrYPb9/A37AvTJWSD6yilkpHwjP/GZPM/nfzDVFjz4iVgWMI9CCUtvp65X4fPeWsdLMJbjlVXF7TrYM94oz8Urp61jJ4gnWAr18hQ+SuCpAe75fd9+WAtb2cGlHu0EiXQ/VQev5+usikuBm5W0FafyYrsrGI3HL3uJKfL2SGWjIMZlXJChvfgy2WYlOsmeUZNxdDkLr9eo9uDlOlIG4anK4vdmddLZmmQST0tIRXhcj2OduO5OMZKWtvDLqo6UoV1OZB9rxlKrvZFrlX/OzNNc6TjnRYSBiWPdvbaI0cOXmbCzK4+NKU6RRqiwatemauiO77UXABCqWABOG1YxKIQlgpTUoyDSW9SYdu9LzkNwkeZlqg4fPNOBhXnJE5CG/oTML4M2+rnKBehC3lx6KVxxWEkCrTcTzIjsW81GM5C5bxyXbLv0E6zHDMfcJX5WsBg8duKQSNieZsgJJjx/SfoLguCsj6oWMtkL3V3cp1DwO+ZsluGBCtCFkTq/sfarNwYJo1QmKUxR/PXK/Fci2yBa6jHYndxmOa+mosjO/5PIv6r1UiZNcmviv1dGJ7v8CkvnIjyoE7/QS5mdzTRHHvMZntCKo3xAvUk4rrM31r3OAdQy1B40LBTTIlPwDzrihWbIbJba8QP2hXJC4VOFK3H9qzSqNIvrl87SQs=
