language: node_js
node_js:
- '6'
script:
- npm run lint
- npm test
- npm run build
deploy:
  provider: npm
  email: opensource@yousee.dk
  skip_cleanup: true
  api_key:
    secure: tiU39I2p/N/L1e0ahsUUbl6IjAdTbqOl+HsQ+AXK5Lb6SGI/8pnJhBgPwVL/YUwXoAP3EDDJIquMuJqE0P03f15gNikHvlv6wVYGSHMpjg0+7iox/6g2BXdHPohcevHiZCikrirI9dOdnoFDH0bf8X3+Wo6epT1q4s6jnhmv57oVcG54fYq3yWEt4JUQ9QslKHzETESUR5VyIUIaHlg4kXRUQDTzrrH0ihHLGOVtyizqNbOJsawFOwFkrYmWtJk8BPF5FViMtuCxqoB4iD+DwdQm+/qZfoqvvdJvFQl48ONpLitVz/iC7Mj/XN8C/bPmXGGEwC0eKjv9he2diV09O31wuZReGRkdxUAnNZd7m55W4hy06GLoBECnLKotL5plbGs0qnz5n2WQqKwwSxYcShB5J/YOQDIdzw/wRNfZ2Q881UpZsTFAKmU1XqAPdWktLEwSkzvQfss/o1/sBVP/JdIATDO2hIm061NiHsL8LeTZvXWZVBIyMiI1uehy7d9J6OQXaMzaWeSHrSjNW5YDUpGT5bNKbpje5ICiSi1zIC8W3x0BCq2F8ZjhRw+IAcdTD0sEYXn735r0TVgv7xpT8LLBOiYh4EmaueXmFcGCt7iVV6imHQUFwzoqANOqvALxYBgsk/Db5TEOoPJ9nJKLCbB/dDxqeZMw8rhqM8Rb6dc=
